version: "3.8"

services:

  # 🔹 MySQL Service
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_management
    ports:
      - "3308:3306"  # Host:Container (use 3308 to avoid conflicts)
    networks:
      - springboot-mysql-net
    volumes:
      - mysql-data:/var/lib/mysql  # ✅ persist MySQL data

  # 🔹 Spring Boot App Service
  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb

    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/user_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_HIKARI_INITIALIZATION-FAIL-TIMEOUT: 60000
      SPRING_DATASOURCE_HIKARI_CONNECTION-TIMEOUT: 60000


    networks:
      - springboot-mysql-net

# 🔗 Shared network
networks:
  springboot-mysql-net: {}

# 💾 Named volume for persistent MySQL data
volumes:
  mysql-data:
