version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      DATABASE_HOST: docker-mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_management
      DATABASE_PORT: 3306
      MYSQL_PASSWORD: root
    networks:
      springboot-mysql-net:

  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    image: springboot-rest-webservices:0.0.3
    ports:
      - "8080:8080"
    environment:
        spring_datasource_url: jdbc:mysql://mysqldb:3306/user_management
        spring_datasource_username: root
        spring_datasource_password: root
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net: